CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Usuario" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(150) NOT NULL,
        "Email" character varying(150),
        "Telefone" character varying(20),
        "CpfCnpj" character varying(18),
        "Categoria" integer NOT NULL,
        "GoogleId" character varying(255),
        "FotoUrl" character varying(500),
        "Cnae" character varying(7),
        "Municipio" character varying(100),
        "Uf" character varying(2),
        "Plano" integer NOT NULL,
        "PlanoValidoAte" timestamp with time zone,
        "AsaasAccountId" character varying(255),
        "AsaasApiKey" character varying(255),
        "StatusContaAsaas" integer NOT NULL,
        "Locale" character varying(5) NOT NULL,
        "Pais" character varying(2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Usuario" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Cliente" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "Nome" character varying(150) NOT NULL,
        "Email" character varying(150),
        "Telefone" character varying(20),
        "Ddd" character varying(5),
        "CpfCnpj" character varying(18),
        "AsaasCustomerId" character varying(255),
        "Cep" character varying(10),
        "Logradouro" character varying(200),
        "Numero" character varying(20),
        "Complemento" character varying(100),
        "Bairro" character varying(100),
        "Cidade" character varying(100),
        "Uf" character varying(2),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Cliente" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cliente_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Plano" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "Tipo" integer NOT NULL,
        "Valor" numeric(18,2) NOT NULL,
        "InicioEm" timestamp with time zone NOT NULL,
        "FimEm" timestamp with time zone,
        "Ativo" boolean NOT NULL,
        "AsaasSubscriptionId" character varying(255),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Plano" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Plano_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Post" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "FotoAntesUrl" character varying(500),
        "FotoDepoisUrl" character varying(500),
        "Legenda" character varying(2200),
        "Hashtags" character varying(500),
        "Publicado" boolean NOT NULL,
        "PublicadoEm" timestamp with time zone,
        "InstagramMediaId" character varying(255),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Post" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Post_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Servico" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "Descricao" character varying(150) NOT NULL,
        "PrecoUnitario" numeric(18,2) NOT NULL,
        "Unidade" character varying(20),
        "Ativo" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Servico" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Servico_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Tarefa" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "Titulo" character varying(200) NOT NULL,
        "Descricao" character varying(1000),
        "Concluida" boolean NOT NULL,
        "Vencimento" timestamp with time zone,
        "GoogleTaskId" character varying(255),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Tarefa" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tarefa_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Evento" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "ClienteId" integer,
        "Titulo" character varying(200) NOT NULL,
        "Descricao" character varying(1000),
        "Inicio" timestamp with time zone NOT NULL,
        "Fim" timestamp with time zone NOT NULL,
        "Status" integer NOT NULL,
        "Local" character varying(300),
        "MeetUrl" character varying(500),
        "GoogleEventId" character varying(255),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Evento" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Evento_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id"),
        CONSTRAINT "FK_Evento_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Proposta" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "ClienteId" integer NOT NULL,
        "Titulo" character varying(200),
        "Status" integer NOT NULL,
        "ValorTotal" numeric(18,2) NOT NULL,
        "Observacoes" character varying(2000),
        "DriveFileId" character varying(500),
        "EnviadaEm" timestamp with time zone,
        "RespondidaEm" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Proposta" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Proposta_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Proposta_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Cobranca" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "ClienteId" integer NOT NULL,
        "PropostaId" integer,
        "FormaPagamento" integer NOT NULL,
        "Status" integer NOT NULL,
        "Valor" numeric(18,2) NOT NULL,
        "Vencimento" timestamp with time zone NOT NULL,
        "Parcelas" integer NOT NULL,
        "Descricao" character varying(255),
        "AsaasPaymentId" character varying(255),
        "PixQrCode" character varying(1000),
        "PixCopiaECola" character varying(500),
        "BoletoUrl" character varying(500),
        "LinkPagamento" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Cobranca" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cobranca_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Cobranca_Proposta_PropostaId" FOREIGN KEY ("PropostaId") REFERENCES "Proposta" ("Id"),
        CONSTRAINT "FK_Cobranca_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "Contrato" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "PropostaId" integer NOT NULL,
        "Status" integer NOT NULL,
        "DriveFileId" character varying(500),
        "Aceito" boolean NOT NULL,
        "AceitoEm" timestamp with time zone,
        "AceitoPor" character varying(150),
        "IpAceite" character varying(45),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Contrato" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Contrato_Proposta_PropostaId" FOREIGN KEY ("PropostaId") REFERENCES "Proposta" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Contrato_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "PropostaItem" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PropostaId" integer NOT NULL,
        "ServicoId" integer,
        "Descricao" character varying(200) NOT NULL,
        "Quantidade" numeric(18,2) NOT NULL,
        "ValorUnitario" numeric(18,2) NOT NULL,
        "Total" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_PropostaItem" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PropostaItem_Proposta_PropostaId" FOREIGN KEY ("PropostaId") REFERENCES "Proposta" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PropostaItem_Servico_ServicoId" FOREIGN KEY ("ServicoId") REFERENCES "Servico" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "LancamentoFinanceiro" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "ClienteId" integer,
        "CobrancaId" integer,
        "Tipo" integer NOT NULL,
        "Status" integer NOT NULL,
        "Descricao" character varying(200) NOT NULL,
        "Categoria" character varying(100),
        "Valor" numeric(18,2) NOT NULL,
        "Vencimento" timestamp with time zone NOT NULL,
        "PagoEm" timestamp with time zone,
        "ComprovanteUrl" character varying(500),
        "Fornecedor" character varying(150),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_LancamentoFinanceiro" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LancamentoFinanceiro_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id"),
        CONSTRAINT "FK_LancamentoFinanceiro_Cobranca_CobrancaId" FOREIGN KEY ("CobrancaId") REFERENCES "Cobranca" ("Id"),
        CONSTRAINT "FK_LancamentoFinanceiro_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE TABLE "NotaFiscal" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "ClienteId" integer NOT NULL,
        "ContratoId" integer,
        "CobrancaId" integer,
        "Status" integer NOT NULL,
        "Valor" numeric(18,2) NOT NULL,
        "DiscriminacaoServico" character varying(2000),
        "Numero" character varying(50),
        "PdfUrl" character varying(500),
        "XmlUrl" character varying(500),
        "EmitidaEm" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_NotaFiscal" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NotaFiscal_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_NotaFiscal_Cobranca_CobrancaId" FOREIGN KEY ("CobrancaId") REFERENCES "Cobranca" ("Id"),
        CONSTRAINT "FK_NotaFiscal_Contrato_ContratoId" FOREIGN KEY ("ContratoId") REFERENCES "Contrato" ("Id"),
        CONSTRAINT "FK_NotaFiscal_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Cliente_UsuarioId" ON "Cliente" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Cobranca_ClienteId" ON "Cobranca" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Cobranca_PropostaId" ON "Cobranca" ("PropostaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Cobranca_UsuarioId" ON "Cobranca" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Contrato_PropostaId" ON "Contrato" ("PropostaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Contrato_UsuarioId" ON "Contrato" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Evento_ClienteId" ON "Evento" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Evento_UsuarioId" ON "Evento" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_LancamentoFinanceiro_ClienteId" ON "LancamentoFinanceiro" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_LancamentoFinanceiro_CobrancaId" ON "LancamentoFinanceiro" ("CobrancaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_LancamentoFinanceiro_UsuarioId" ON "LancamentoFinanceiro" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_NotaFiscal_ClienteId" ON "NotaFiscal" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_NotaFiscal_CobrancaId" ON "NotaFiscal" ("CobrancaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_NotaFiscal_ContratoId" ON "NotaFiscal" ("ContratoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_NotaFiscal_UsuarioId" ON "NotaFiscal" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Plano_UsuarioId" ON "Plano" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Post_UsuarioId" ON "Post" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Proposta_ClienteId" ON "Proposta" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Proposta_UsuarioId" ON "Proposta" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_PropostaItem_PropostaId" ON "PropostaItem" ("PropostaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_PropostaItem_ServicoId" ON "PropostaItem" ("ServicoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Servico_UsuarioId" ON "Servico" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    CREATE INDEX "IX_Tarefa_UsuarioId" ON "Tarefa" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629152751_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629152751_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

