CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "InboxState" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MessageId" uuid NOT NULL,
        "ConsumerId" uuid NOT NULL,
        "LockId" uuid NOT NULL,
        "RowVersion" bytea,
        "Received" timestamp with time zone NOT NULL,
        "ReceiveCount" integer NOT NULL,
        "ExpirationTime" timestamp with time zone,
        "Consumed" timestamp with time zone,
        "Delivered" timestamp with time zone,
        "LastSequenceNumber" bigint,
        CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "OtpCode" (
        "Id" uuid NOT NULL,
        "Identificador" character varying(150) NOT NULL,
        "CodigoHash" character varying(200) NOT NULL,
        "ExpiraEm" timestamp with time zone NOT NULL,
        "Tentativas" integer NOT NULL,
        "Usado" boolean NOT NULL,
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_OtpCode" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "OutboxState" (
        "OutboxId" uuid NOT NULL,
        "LockId" uuid NOT NULL,
        "RowVersion" bytea,
        "Created" timestamp with time zone NOT NULL,
        "Delivered" timestamp with time zone,
        "LastSequenceNumber" bigint,
        CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "SyncWatermark" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "DispositivoId" uuid NOT NULL,
        "Modulo" character varying(80) NOT NULL,
        "UltimoSyncEm" timestamp with time zone NOT NULL,
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_SyncWatermark" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Usuario" (
        "Id" uuid NOT NULL,
        "Nome" character varying(150) NOT NULL,
        "Email" character varying(150),
        "Telefone" character varying(20),
        "TelefoneVerificado" boolean NOT NULL,
        "CpfCnpj" character varying(18),
        "Categoria" integer NOT NULL,
        "GoogleId" character varying(255),
        "FotoUrl" character varying(500),
        "Cnae" character varying(7),
        "Municipio" character varying(100),
        "Uf" character varying(2),
        "Plano" integer NOT NULL,
        "PlanoValidoAte" timestamp with time zone,
        "AsaasAccountId" character varying(255),
        "AsaasApiKey" character varying(255),
        "StatusContaAsaas" integer NOT NULL,
        "Locale" character varying(5) NOT NULL,
        "Pais" character varying(2) NOT NULL,
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Usuario" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "OutboxMessage" (
        "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EnqueueTime" timestamp with time zone,
        "SentTime" timestamp with time zone NOT NULL,
        "Headers" text,
        "Properties" text,
        "InboxMessageId" uuid,
        "InboxConsumerId" uuid,
        "OutboxId" uuid,
        "MessageId" uuid NOT NULL,
        "ContentType" character varying(256) NOT NULL,
        "MessageType" text NOT NULL,
        "Body" text NOT NULL,
        "ConversationId" uuid,
        "CorrelationId" uuid,
        "InitiatorId" uuid,
        "RequestId" uuid,
        "SourceAddress" character varying(256),
        "DestinationAddress" character varying(256),
        "ResponseAddress" character varying(256),
        "FaultAddress" character varying(256),
        "ExpirationTime" timestamp with time zone,
        CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber"),
        CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId" FOREIGN KEY ("InboxMessageId", "InboxConsumerId") REFERENCES "InboxState" ("MessageId", "ConsumerId"),
        CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId" FOREIGN KEY ("OutboxId") REFERENCES "OutboxState" ("OutboxId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Cliente" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "Nome" character varying(150) NOT NULL,
        "Email" character varying(150),
        "Telefone" character varying(20),
        "Ddd" character varying(5),
        "CpfCnpj" character varying(18),
        "AsaasCustomerId" character varying(255),
        "Cep" character varying(10),
        "Logradouro" character varying(200),
        "Numero" character varying(20),
        "Complemento" character varying(100),
        "Bairro" character varying(100),
        "Cidade" character varying(100),
        "Uf" character varying(2),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Cliente" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cliente_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Dispositivo" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "DeviceId" character varying(200) NOT NULL,
        "Nome" character varying(150),
        "Plataforma" character varying(50),
        "AppVersion" character varying(50),
        "Ip" character varying(45),
        "UserAgent" character varying(300),
        "UltimoAcessoEm" timestamp with time zone,
        "UltimaSyncEm" timestamp with time zone,
        "Revogado" boolean NOT NULL,
        "RevogadoEm" timestamp with time zone,
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Dispositivo" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Dispositivo_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Plano" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "Tipo" integer NOT NULL,
        "Valor" numeric(18,2) NOT NULL,
        "InicioEm" timestamp with time zone NOT NULL,
        "FimEm" timestamp with time zone,
        "Ativo" boolean NOT NULL,
        "AsaasSubscriptionId" character varying(255),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Plano" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Plano_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Post" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "FotoAntesUrl" character varying(500),
        "FotoDepoisUrl" character varying(500),
        "Legenda" character varying(2200),
        "Hashtags" character varying(500),
        "Publicado" boolean NOT NULL,
        "PublicadoEm" timestamp with time zone,
        "InstagramMediaId" character varying(255),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Post" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Post_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Servico" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "Descricao" character varying(150) NOT NULL,
        "PrecoUnitario" numeric(18,2) NOT NULL,
        "Unidade" character varying(20),
        "Ativo" boolean NOT NULL,
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Servico" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Servico_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Tarefa" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "Titulo" character varying(200) NOT NULL,
        "Descricao" character varying(1000),
        "Concluida" boolean NOT NULL,
        "Vencimento" timestamp with time zone,
        "GoogleTaskId" character varying(255),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Tarefa" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tarefa_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Evento" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "ClienteId" uuid,
        "Titulo" character varying(200) NOT NULL,
        "Descricao" character varying(1000),
        "Inicio" timestamp with time zone NOT NULL,
        "Fim" timestamp with time zone NOT NULL,
        "Status" integer NOT NULL,
        "Local" character varying(300),
        "MeetUrl" character varying(500),
        "GoogleEventId" character varying(255),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Evento" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Evento_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id"),
        CONSTRAINT "FK_Evento_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Proposta" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "ClienteId" uuid NOT NULL,
        "Titulo" character varying(200),
        "Status" integer NOT NULL,
        "ValorTotal" numeric(18,2) NOT NULL,
        "Observacoes" character varying(2000),
        "DriveFileId" character varying(500),
        "EnviadaEm" timestamp with time zone,
        "RespondidaEm" timestamp with time zone,
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Proposta" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Proposta_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Proposta_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "RefreshToken" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "DispositivoId" uuid NOT NULL,
        "TokenHash" character varying(200) NOT NULL,
        "ExpiraEm" timestamp with time zone NOT NULL,
        "Revogado" boolean NOT NULL,
        "RevogadoEm" timestamp with time zone,
        "SubstituidoPorHash" character varying(200),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshToken_Dispositivo_DispositivoId" FOREIGN KEY ("DispositivoId") REFERENCES "Dispositivo" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RefreshToken_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Cobranca" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "ClienteId" uuid NOT NULL,
        "PropostaId" uuid,
        "FormaPagamento" integer NOT NULL,
        "Status" integer NOT NULL,
        "Valor" numeric(18,2) NOT NULL,
        "Vencimento" timestamp with time zone NOT NULL,
        "Parcelas" integer NOT NULL,
        "Descricao" character varying(255),
        "AsaasPaymentId" character varying(255),
        "PixQrCode" character varying(1000),
        "PixCopiaECola" character varying(500),
        "BoletoUrl" character varying(500),
        "LinkPagamento" character varying(500),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Cobranca" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cobranca_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Cobranca_Proposta_PropostaId" FOREIGN KEY ("PropostaId") REFERENCES "Proposta" ("Id"),
        CONSTRAINT "FK_Cobranca_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "Contrato" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "PropostaId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "DriveFileId" character varying(500),
        "Aceito" boolean NOT NULL,
        "AceitoEm" timestamp with time zone,
        "AceitoPor" character varying(150),
        "IpAceite" character varying(45),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Contrato" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Contrato_Proposta_PropostaId" FOREIGN KEY ("PropostaId") REFERENCES "Proposta" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Contrato_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "PropostaItem" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "PropostaId" uuid NOT NULL,
        "ServicoId" uuid,
        "Descricao" character varying(200) NOT NULL,
        "Quantidade" numeric(18,2) NOT NULL,
        "ValorUnitario" numeric(18,2) NOT NULL,
        "Total" numeric(18,2) NOT NULL,
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_PropostaItem" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PropostaItem_Proposta_PropostaId" FOREIGN KEY ("PropostaId") REFERENCES "Proposta" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PropostaItem_Servico_ServicoId" FOREIGN KEY ("ServicoId") REFERENCES "Servico" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "LancamentoFinanceiro" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "ClienteId" uuid,
        "CobrancaId" uuid,
        "Tipo" integer NOT NULL,
        "Status" integer NOT NULL,
        "Descricao" character varying(200) NOT NULL,
        "Categoria" character varying(100),
        "Valor" numeric(18,2) NOT NULL,
        "Vencimento" timestamp with time zone NOT NULL,
        "PagoEm" timestamp with time zone,
        "ComprovanteUrl" character varying(500),
        "Fornecedor" character varying(150),
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_LancamentoFinanceiro" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LancamentoFinanceiro_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id"),
        CONSTRAINT "FK_LancamentoFinanceiro_Cobranca_CobrancaId" FOREIGN KEY ("CobrancaId") REFERENCES "Cobranca" ("Id"),
        CONSTRAINT "FK_LancamentoFinanceiro_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE TABLE "NotaFiscal" (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "ClienteId" uuid NOT NULL,
        "ContratoId" uuid,
        "CobrancaId" uuid,
        "Status" integer NOT NULL,
        "Valor" numeric(18,2) NOT NULL,
        "DiscriminacaoServico" character varying(2000),
        "Numero" character varying(50),
        "PdfUrl" character varying(500),
        "XmlUrl" character varying(500),
        "EmitidaEm" timestamp with time zone,
        "Version" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_NotaFiscal" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NotaFiscal_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_NotaFiscal_Cobranca_CobrancaId" FOREIGN KEY ("CobrancaId") REFERENCES "Cobranca" ("Id"),
        CONSTRAINT "FK_NotaFiscal_Contrato_ContratoId" FOREIGN KEY ("ContratoId") REFERENCES "Contrato" ("Id"),
        CONSTRAINT "FK_NotaFiscal_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Cliente_UsuarioId" ON "Cliente" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Cobranca_ClienteId" ON "Cobranca" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Cobranca_PropostaId" ON "Cobranca" ("PropostaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Cobranca_UsuarioId" ON "Cobranca" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Contrato_PropostaId" ON "Contrato" ("PropostaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Contrato_UsuarioId" ON "Contrato" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Dispositivo_UsuarioId" ON "Dispositivo" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Dispositivo_UsuarioId_DeviceId" ON "Dispositivo" ("UsuarioId", "DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Evento_ClienteId" ON "Evento" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Evento_UsuarioId" ON "Evento" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_InboxState_Delivered" ON "InboxState" ("Delivered");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_LancamentoFinanceiro_ClienteId" ON "LancamentoFinanceiro" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_LancamentoFinanceiro_CobrancaId" ON "LancamentoFinanceiro" ("CobrancaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_LancamentoFinanceiro_UsuarioId" ON "LancamentoFinanceiro" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_NotaFiscal_ClienteId" ON "NotaFiscal" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_NotaFiscal_CobrancaId" ON "NotaFiscal" ("CobrancaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_NotaFiscal_ContratoId" ON "NotaFiscal" ("ContratoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_NotaFiscal_UsuarioId" ON "NotaFiscal" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_OtpCode_Identificador" ON "OtpCode" ("Identificador");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessage_EnqueueTime" ON "OutboxMessage" ("EnqueueTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessage_ExpirationTime" ON "OutboxMessage" ("ExpirationTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber" ON "OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber" ON "OutboxMessage" ("OutboxId", "SequenceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_OutboxState_Created" ON "OutboxState" ("Created");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Plano_UsuarioId" ON "Plano" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Post_UsuarioId" ON "Post" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Proposta_ClienteId" ON "Proposta" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Proposta_UsuarioId" ON "Proposta" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_PropostaItem_PropostaId" ON "PropostaItem" ("PropostaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_PropostaItem_ServicoId" ON "PropostaItem" ("ServicoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_PropostaItem_UsuarioId" ON "PropostaItem" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_RefreshToken_DispositivoId" ON "RefreshToken" ("DispositivoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_RefreshToken_TokenHash" ON "RefreshToken" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_RefreshToken_UsuarioId" ON "RefreshToken" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Servico_UsuarioId" ON "Servico" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_SyncWatermark_UsuarioId" ON "SyncWatermark" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SyncWatermark_UsuarioId_DispositivoId_Modulo" ON "SyncWatermark" ("UsuarioId", "DispositivoId", "Modulo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    CREATE INDEX "IX_Tarefa_UsuarioId" ON "Tarefa" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630003805_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630003805_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630005000_OutboxArquiteturaSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Arquitetura') THEN
            CREATE SCHEMA "Arquitetura";
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630005000_OutboxArquiteturaSchema') THEN
    ALTER TABLE "InboxState" SET SCHEMA "Arquitetura";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630005000_OutboxArquiteturaSchema') THEN
    ALTER TABLE "OutboxMessage" SET SCHEMA "Arquitetura";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630005000_OutboxArquiteturaSchema') THEN
    ALTER TABLE "OutboxState" SET SCHEMA "Arquitetura";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630005000_OutboxArquiteturaSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630005000_OutboxArquiteturaSchema', '10.0.0');
    END IF;
END $EF$;
COMMIT;

