// <auto-generated />
using Libify.Infraestructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Libify.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630120000_AsaasIntegracao")]
    partial class AsaasIntegracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Modelo alvo registrado no snapshot após migrations subsequentes.
#pragma warning restore 612, 618
        }
    }
}
