// <auto-generated />
using Libify.Infraestructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Libify.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701120000_PropostaLinkPublico")]
    partial class PropostaLinkPublico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Modelo alvo registrado no AppDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
